---
title: "Linear Regression"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(base.url='https://github.com/.../raw/.../')



create_gitpath <- function(user, repo, branch = 'master'){
   paste0(paste('https://github.com', user, repo, 'raw', branch, sep = '/'),'/')
}

my_repo <- create_gitpath('Minkooking',
                          'Machine-Learning-Algorithm')

knit.github <- function(..., git_url){
 old_url <- opts_knit$get('base.url')
 on.exit(opts_knit$set(base.url = old_url))
 opts_knit$set(base.url  = git_url)
 knit(..., envir = parent.frame())
}

```

#### simple linear regression
```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)

n = 300
set.seed(1)
x = runif(n,min = 1,max = 10)
y = -1 + 3 * x + rnorm(n, 0, 1)

ggplot() + geom_point(aes(x, y))
```


#### estimate of true beta
```{r}
X = cbind(1, x)
(beta = solve(t(X) %*% X) %*% t(X) %*% y)

ggplot() + geom_point(aes(x, y)) + 
  geom_line(aes(x, -1 + 3 * x, color = 'true'), lwd = 1.5) + 
  geom_line(aes(x, X %*% beta, color = 'estimated'),
            lwd = 1.5) + 
  scale_color_manual(breaks = c('true','estimated'),
                      values = c('blue', 'red'))

# R built-in function 
lm(y~x)$coefficients

```

